name: Deploy

on:
  push:
    branches:
      - main

jobs:
  buildAndTest:
    uses: sp0rk/chaffinch-gha/.github/workflows/buildAndTest.yml@main
    secrets:
      jitPackToken: ""
    with:
      coverageBadge: true
      coverageReport: false

  ktlint:
    uses: sp0rk/chaffinch-gha/.github/workflows/lint.yml@main
    secrets:
      REVIEWDOG_TOKEN: ${{secrets.REVIEWDOG_TOKEN}}
    with:
      failOnError: true
      reporter: "github-check"

  deploy:
    needs: [buildAndTest, ktlint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Read version
        run: cat ./buildSrc/src/main/java/Config.kt | grep 'const val lib =' | cut -d '"' -f 2 | (echo -n version= && cat) >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: "${{ env.version }}"