name: Run Lint

on:
  workflow_call:
    secrets:
      REVIEWDOG_TOKEN:
        required: true
        description: "Token for ReviewDog To report lint issues in PRs"
    inputs:
      failOnError:
        type: boolean
        required: true
        description: "Fail action on lint error?"
      reporter:
        type: string
        required: true
        description: "github-pr-review | github-check"

jobs:
  ktlint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: KtLint
        uses: ScaCap/action-ktlint@master
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.REVIEWDOG_TOKEN }}
        with:
          github_token: ${{ secrets.REVIEWDOG_TOKEN }}
          reporter: ${{inputs.reporter}}
          level: warning
          filter_mode: nofilter
          fail_on_error: ${{inputs.failOnError}}
