name: Bump version
on:
  push:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Read version
        run: cat ./buildSrc/src/main/java/Config.kt | grep lib | cut -d '"' -f 2 >> $VERSION
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: $VERSION