name: Validate

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  buildAndTest:
    uses: sp0rk/chaffinch-lib/.github/workflows/buildAndTest.yml@main
    with:
      coverageBadge: false
      coverageReport: true

  ktlint:
    uses: sp0rk/chaffinch-lib/.github/workflows/lint.yml@main
    secrets:
      REVIEWDOG_TOKEN: ${{secrets.REVIEWDOG_TOKEN}}
    with:
      failOnError: true
      reporter: "github-pr-review"

  approve:
    runs-on: ubuntu-latest
    needs: [buildAndTest, ktlint]
    steps:
      - name: Approve
        uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}